### PR TITLE
Enable `risc0-zkvm/client` feature by default

### LINKED ISSUE #157: Unable to build prover without CUDA/Metal acceleration
I have _AMD Radeon RX 580_ which cannot be accelerated in Risc0 zkVM, therefore I am building Kairos prover without `cuda` / `metal` features enabled.

Errors reported when running `cargo build -p kairos-prover-risc0-server`:

```
error[E0432]: unresolved imports `risc0_zkvm::ExecutorEnv`, `risc0_zkvm::Prover`
   --> kairos-prover-risc0-server/src/main.rs:10:18
    |
10  | use risc0_zkvm::{ExecutorEnv, Prover, Receipt};
    |                  ^^^^^^^^^^^  ^^^^^^ no `Prover` in the root
    |                  |
    |                  no `ExecutorEnv` in the root
    |
note: found an item that was configured out
   --> /home/andrew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-1.0.2/src/lib.rs:123:19
    |
123 |             env::{ExecutorEnv, ExecutorEnvBuilder},
    |                   ^^^^^^^^^^^
note: found an item that was configured out
   --> /home/andrew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-1.0.2/src/lib.rs:126:27
    |
126 |                 Executor, Prover, ProverOpts, ReceiptKind,
    |                           ^^^^^^

error[E0433]: failed to resolve: could not find `ExternalProver` in `risc0_zkvm`
   --> kairos-prover-risc0-server/src/main.rs:84:26
    |
84  |         _ => risc0_zkvm::ExternalProver::new(
    |                          ^^^^^^^^^^^^^^ could not find `ExternalProver` in `risc0_zkvm`
    |
note: found an item that was configured out
   --> /home/andrew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-1.0.2/src/lib.rs:125:83
    |
125 |                 bonsai::BonsaiProver, default_executor, default_prover, external::ExternalProver,
    |                                                                                   ^^^^^^^^^^^^^^

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `kairos-prover-risc0-server` (bin "kairos-prover-risc0-server") due to 2 previous errors
```

### PR DESCRIPTION
**Pull request by koxu1996**
Fixes #157.

### CODE REVIEW

**Comment by Avi-D-coder** [comment]
I don't want to enable `prove` by default because it makes rust-analyzer spin up an endless c++ complication and breaks the lsp. I am not sure why the you are hitting #157. I can build without prove.

Are you in the devshell `nix develop .#risczero`?

**Comment by koxu1996** [comment]
@Avi-D-coder I removed it from default features - https://github.com/cspr-rad/kairos/pull/158/commits/3bd10ad66c1cff4802f9a8e8f6dbe7437766cd81.

I tried building in the Nix shell - same result:

```sh
$ nix develop .#risczero
$ cd ./kairos-prover
$ cargo build -p kairos-prover-risc0-server
# compilation fails as described in #157
```

If there is no `prove` enabled then all Risc0 proving items are simply configured out.

**Comment by marijanp** [comment]
@koxu1996 I can't reproduce the error

**Comment by koxu1996** [comment]
@marijanp Are you compiling it without metal/cuda feature enabled?

**Comment by Avi-D-coder** [comment]
Could we rename the feature something like cpu prove

**Comment by koxu1996** [comment]
> I'd like to make it clear this builds that prover again.

I didn't want to build prover again, but rather make `ExternalProver` available in the code. Therefore `client` feature is more suitable here:

image

It should be enabled by default, as it's a default fallback:

image

@Avi-D-coder Please check updated PR.

**Review by marijanp — APPROVED** [review]

**Review by Avi-D-coder — APPROVED** [review]

**Pull request merged**
