### PR TITLE
Update rust version, cargo packages, flake inputs, except risc0

### PR DESCRIPTION
**Pull request by Avi-D-coder**

### CODE REVIEW

**Review by marijanp — APPROVED** [review]

**Review by koxu1996 — APPROVED** [review]
LGTM

**Comment by Avi-D-coder** [comment]
ah, the signed commit check does not appear to consider actions taken by the github web ui verified. I’ll have to rebase locally tomorrow.

**Comment by marijanp** [comment]
@Avi-D-coder seems like your git is not configured properly. The signatures are still missing.

**Comment by Avi-D-coder** [comment]
> @Avi-D-coder seems like your git is not configured properly. The signatures are still missing.

I signed on the cli, that worked, and was passing the check.
I then used Github's web UI to rebase, and that removed the signatures.
Is there a way to get the check to recognize commit's from Github web ui as verified?

**Comment by Avi-D-coder** [comment]
> > @Avi-D-coder seems like your git is not configured properly. The signatures are still missing.
> 
> I signed on the cli, that worked, and was passing the check. I then used Github's web UI to rebase, and that removed the signatures. Is there a way to get the check to recognize commit's from Github web ui as verified?

I guess not, that sucks.
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#signature-verification-for-rebase-and-merge

**Review by marijanp — APPROVED** [review]

**Pull request merged**
