### PR TITLE
Add `no_std` support to `kairos-tx`

### LINKED ISSUE #60: Support for `no_std` in `kairos-tx`
Reported by @xcthulhu and @jonas089 during _Kairos - Tx Format_ deep dive call.

Btw. `no_std` is NOT requirement for Casper contracts, but it is beneficial for creating smaller binaries.

### PR DESCRIPTION
**Pull request by koxu1996**
This PR adds support for `no_std` in `kairos-tx` :rocket:.

**Note:** I replaced `thiserror` with plain enum implementing `fmt::Display`, as advised by @Avi-D-coder :clap:.

Closes #60.

### CODE REVIEW

**Comment by Avi-D-coder** [comment]
It would be nice to have a github action to build this with `--no-default-features`

**Comment by Avi-D-coder** [comment]
Just see if it builds correctly.

**Comment by koxu1996** [comment]
@Avi-D-coder I added extra CI check - it passed successfully:

image

I guess we need something similar for `kairos-trie`.

**Comment by Avi-D-coder** [comment]
Yeah added it now

**Comment by Avi-D-coder** [comment]
ignore the hercules failures they are unrelated.

**Review by Avi-D-coder — APPROVED** [review]
LGTM

**Review by jonas089 — APPROVED** [review]

**Pull request merged**
